// Code generated by protoc-gen-go.
// source: post.proto
// DO NOT EDIT!

/*
Package bar is a generated protocol buffer package.

It is generated from these files:
	post.proto
	server.proto

It has these top-level messages:
	AddPostReq
	AddPostRsp
*/
package bar

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddPostReq struct {
	Tid     int32  `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Uid     int32  `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (m *AddPostReq) Reset()                    { *m = AddPostReq{} }
func (m *AddPostReq) String() string            { return proto.CompactTextString(m) }
func (*AddPostReq) ProtoMessage()               {}
func (*AddPostReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddPostReq) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *AddPostReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AddPostReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddPostReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type AddPostRsp struct {
	Status int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Qid    string `protobuf:"bytes,2,opt,name=qid" json:"qid,omitempty"`
}

func (m *AddPostRsp) Reset()                    { *m = AddPostRsp{} }
func (m *AddPostRsp) String() string            { return proto.CompactTextString(m) }
func (*AddPostRsp) ProtoMessage()               {}
func (*AddPostRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddPostRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddPostRsp) GetQid() string {
	if m != nil {
		return m.Qid
	}
	return ""
}

func init() {
	proto.RegisterType((*AddPostReq)(nil), "bar.AddPostReq")
	proto.RegisterType((*AddPostRsp)(nil), "bar.AddPostRsp")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x45, 0x89, 0xb1, 0x95, 0xbe, 0x49, 0x82, 0x48, 0xc6, 0xd2, 0xa9, 0x93, 0x8b, 0xe0, 0xee,
	0x1f, 0x48, 0xbe, 0xc0, 0xd6, 0x64, 0x08, 0x48, 0x93, 0xf6, 0xdd, 0xfc, 0xbf, 0xa4, 0x8d, 0x74,
	0xbb, 0xe7, 0x2c, 0xe7, 0x12, 0xc5, 0xc0, 0xb8, 0xc5, 0x25, 0x20, 0x28, 0x39, 0x0e, 0x4b, 0xf7,
	0x26, 0x7a, 0x5a, 0xfb, 0x0a, 0x0c, 0xe3, 0x66, 0x75, 0x26, 0x09, 0x6f, 0xb5, 0x68, 0x45, 0x5f,
	0x99, 0x3c, 0xb3, 0x49, 0xde, 0xea, 0xc3, 0x66, 0x92, 0xb7, 0xea, 0x42, 0x15, 0x3c, 0xbe, 0x4e,
	0xcb, 0x56, 0xf4, 0x8d, 0xd9, 0x40, 0x69, 0x3a, 0x7d, 0xc2, 0x04, 0x37, 0x41, 0x1f, 0x57, 0xff,
	0xc7, 0xee, 0xb1, 0x17, 0x38, 0xaa, 0x2b, 0xd5, 0x8c, 0x01, 0x89, 0x4b, 0xa4, 0x50, 0xee, 0xcc,
	0xa5, 0xd3, 0x98, 0x3c, 0xc7, 0x7a, 0x7d, 0x79, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x67, 0xa8,
	0x27, 0xbe, 0xb3, 0x00, 0x00, 0x00,
}
